### ISSUE TITLE
Change Of Payment Gateway

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#10]
Hi Jeffy,

As discussed over the call, it seems that RazorPay might long to get things sorter out. Hence you may please change the Payment Gateway from Razor Pay to PayyuMoney. (For time being)

Once the RBI RazorPay issues are sorted out , we can shift / route back to the RazorPay as it would the best Vendor and inform the existing users to update the app (if needed).

Kindly do the needful as discussed.

Thanks and Regards,
Sunil Vijayan

**Comment by ZateLabClients** [comment]
Here is the list of online payment aggregator is allowed to operate, RBI full list:

Read more at:
https://economictimes.indiatimes.com/wealth/spend/paytm-google-pay-amazon-pay-payu-which-online-payment-aggregator-is-allowed-to-operate-which-isnt-rbi-full-list/articleshow/97975237.cms?from=mdr

**Comment by ZateLabClients** [comment]
Completed
