### ISSUE TITLE
Subscription Packages created but Not Visible in webapp

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#13]
Hi Jeffy,

As discussed, i have created the subscription packages and enabled them as you advised but even though the Packages are not visible /reflecting in the  web app subscribe option. 

I have attached the screenshots for reference. Kindly look into this.

Regards,
Sneha Krishnan![image](https://user-images.githubusercontent.com/121546719/229787371-6774e16c-8b4f-4000-9677-ea359667ff57.jpeg)

**Comment by ZateLabClients** [comment]
Completed
