### ISSUE TITLE
Subscription packages section is not scrolling down

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#14]
Hi Jeffy, 

The Subscription section is not scrolling down ( In Phones /Tabs). 

When we forcefully dragging down the packages are scrolling but once we take the finger from the screen then it scrolls back to the  top. 

Please look into this and help us to resolve this issue 

Thanks and Regards,
Sunil vijayan

**Comment by ZateLabClients** [comment]
completed
