### ISSUE TITLE
Forget password Not working

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#15]
Hi Jeffy,

While giving forget password the option to enter password is coming but after giving the password/ new password,it is not helping to reset the password. The page is simply showing as loading

Please find the attached screenshot for the reference.

Regards,
Sunil vijayan

 [![image](https://user-images.githubusercontent.com/121546719/233954922-ecdda100-9ce7-4f8f-a643-b3aa4151d1a0.jpeg)]()

**Comment by ZateLabClients** [comment]
completed
