### ISSUE TITLE
Login page showing the user ID as "1111111111 "by default

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#16]
Hi Jeffy,

The login page is showing (111111111) by default. Kindly look into this and do the needful.

Regards,
Sunil 

![image](https://user-images.githubusercontent.com/121546719/233955814-3f8ef41f-c597-4a87-bb4a-aa7d68e0f886.jpeg)

**Comment by ZateLabClients** [comment]
completed for web.
Android update added to playstore. (waiting for approval)
