### ISSUE TITLE
Important Updates that are pending

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#17]
Dear Jeffy ,

Some of the important things are found missing. 
Please find the pending updates as mentioned below.

1. Photo Water mark should be fade / high opacity and should come across the photo. ( Reference Screenshot attached below)

2. Customer ID is not visible to the users. ( Reference screenshot as attached below)

3. Forgot password not working. (Keeps on loading) Screenshot below.

4. Login Page is showing 1111111 in login by default.

5. Agent code /Reference code option not found. 
As discussed earlier this option should be there in the last of a new profile Registration so that we can understand who referred this customer. (commission amount will be paid according to this)

Model/ Example
--------------

Are you an consultant? :
Yes / No

If Yes

Enter Consultant code : xxxx

6. Payment Gateway (waiting for approval ) Ignore for now.

Kindly check and do the needful at the earliest.

Thanks and Regards,
Sunil Vijayan![image](https://user-images.githubusercontent.com/121546719/234244852-494d5083-5507-426b-8c1f-a9b902fa9e93.jpeg)![image](https://user-images.githubusercontent.com/121546719/234244942-56028184-863d-4ca9-9d61-65428e3829df.jpeg)![image](https://user-images.githubusercontent.com/121546719/234244993-87a2d255-8f9a-4532-8598-b5b1ceb149f7.jpeg)

**Comment by ZateLabClients** [comment]
all except (Customer ID is not visible to the users. ( Reference screenshot as attached below)) is completed. 
(Customer ID is not visible to the users. ( Reference screenshot as attached below)) added as new issue #19
