### ISSUE TITLE
Mobile No not Visible in Control Panel.

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#18]
Hi Jeffy,

The mobile numbers are not visible on the Control panel. Kindly make it visible.

Screenshot is attached below for reference. Kindly check

Thanks and Regards,
Sunil 
![image](https://user-images.githubusercontent.com/121546719/234255607-b3a00434-b042-4873-8962-7434fb83cfc7.jpeg)

**Comment by ZateLabClients** [comment]
completed
