### ISSUE TITLE
Change all Partners preference options to Un Mandate.

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#22]
Hi Jeffy,

As of now all Partners preference options are mandate to be filled.

Please make it Non Mandatory so that the users can skip which they dont want to add in their preferences.

Thanks and Regards,
Sneha Sunil

**Comment by myheramatrimony** [comment]
Hi Jeffy,

Is there Any updates on this one ?

Please let me know once its done.

Regards,
Sunil

**Comment by ZateLabClients** [comment]
closed this issue as there no response after the discussion
