### ISSUE TITLE
Scrolling issues in selection options.

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#23]
Hi Jeffy,

In partners preference the educational preference options is not scrolling down untill we forcefully drag it down . 

Once we released the touch from phone then it go to top automatically. Please look into this and fix this aswell . 

Also the "Any" option is not visible in the "Education" and "Salary" preference option.Kindly Any in all .

 (In admin console ANY option there but Not visible in the Application). 

Kindly request you to do the needful.

Thanks and Regards,
Sneha Sunil

**Comment by ZateLabClients** [comment]
Please attach a video here or in whatsapp.
I didnt see any such scroll issues

**Comment by ZateLabClients** [comment]
scrolling issue fixed. update it from playsore
