### ISSUE TITLE
Subscription not reflecting after payment Done

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#28]
After a successful subscription payment is done, the package offers are not reflecting or activated in the customer's account.

This is supposed to be automatically updated in the customer's account after customer subscription is successful

![image](https://github.com/ZateLabClients/hera_matrimony_issues/assets/121546719/7ed59ee9-3380-40ef-83cc-c88fdc28f772)

![image](https://github.com/ZateLabClients/hera_matrimony_issues/assets/121546719/b477b9d1-eb74-44b2-b628-874dffb6ccf2)

**Comment by ZateLabClients** [comment]
completed. Verify from your side too
