### ISSUE TITLE
Subscription Successful Notification Message Modification Required

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#29]
As discussed please change the current Payment successful notification message From "Your order has been placed"  - To - " Your payment has been processed successfully . Thank you.!"

A screenshot has been attached for your reference. Kindly look into this and make the necessary changes.

![image](https://github.com/ZateLabClients/hera_matrimony_issues/assets/121546719/7b90fb74-8239-45d5-938c-1941a5b9a6e8)

**Comment by ZateLabClients** [comment]
completed. Please test from your side too
