### ISSUE TITLE
Add Option to Download Data to Excel

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#30]
Dear Jeffy,

Kindly add an option to export data to Excel sheet in the Console so that I can flitter and download the data required along with the referral code. 

Regards,
Sunil 

![image](https://github.com/ZateLabClients/hera_matrimony_issues/assets/121546719/3c0e530e-b208-4c2d-a398-8aa51c1a1ca4)

![image](https://github.com/ZateLabClients/hera_matrimony_issues/assets/121546719/a6865e15-abe4-406d-a134-1fa48c233525)

**Comment by ZateLabClients** [comment]
1. http://134.122.125.172:888/phpmyadmin_3980d4a099f54e66/
    Login username: hera_client
    Login pass: sent u via whatsapp
2. Watch the attached video: https://drive.google.com/file/d/1nifBBUyUjm4KGlwEcn2O-9ulnCRzN093/view?usp=sharing

**Comment by ZateLabClients** [comment]
completed
