### ISSUE TITLE
Add Agent code

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#6]
Hi jeffy , 

As discussed yesterday , 
Please add the below option in end of registration.

* Are you an consultant? : 

 Yes / No

If Yes 

* Enter Consultant code : xxxx

( so that I can get the details of agent who brought the customer)
Regards, 
Sunil vjn

**Comment by ZateLabClients** [comment]
completed.
You can see the agentcode/referal code in users list in admin panel
