### ISSUE TITLE
Registration failed // Drop down selection options not found.

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#7]
Hi Jeffy, 

There are some auto fill/ drop down options missing in while registration so that I am not able to complete the profile Registration . Please find the below screenshot for the reference 

![image](https://user-images.githubusercontent.com/121546719/221548632-4ca38b80-e9c1-4209-b6f3-]()]().jpeg![image](https://user-images.githubusercontent.com/121546719/221548731-2fdd4cfd-5df4-4c41-b04d-45b8d03bb040.jpeg)]()![image](https://user-images.githubusercontent.com/121546719/221548839-d2ef905f-8e3f-4c39-bf0b-f6d12c5d04c3.jpeg)

Please check and do the needful.

Regards, 
Sunil vjn

**Comment by myheramatrimony** [comment]
Hi Jeffy,

Jeffy,

Please find the below options that are not working while registering..

👇🏻



Hobbies and Interests 
———————————-

Hobbies 
Interest 
Sports/ fitness
Prefered dress style 
Spoken languages






Religious Preference 
—————————-

Cast
Star

Professional preference 
———————————-

Education 
Employeed in
Occupation

Location Preferences 
———————————

Country
Residing state

END :-
----------------------------

Regards,
Sunil

**Comment by ZateLabClients** [comment]
solved
