### ISSUE TITLE
Tittle name change required || Name fade required.

### ISSUE THREAD

**Issue by myheramatrimony** [ZateLabClients/hera_matrimony_issues#9]
Hi Jeffy, 

There is a tittle named "Moon" that has to be changed to/ replaced by the name " Raasi". 

And also as discussed earlier the Name after Space should be faded / not visible. 

Example: if the full name is "Sneha Krishnan MP". Then the users should be able to see only the First name , which is " Sneha" and rest of name " Krishnan mp" should be faded. 

(So that the users wont be able to search and find the profiles in Social Medias)

Please note this point.

Thanks and Regards, 
Sunil vijayan

**Comment by ZateLabClients** [comment]
Moon text replaced as Raasi in "Edit profile/ Register Profile" pages

**Comment by ZateLabClients** [comment]
If the user is not subscribed, only first name will be visible. It is already implement in our app. Is there anything wrong in our app?

**Comment by ZateLabClients** [comment]
completed
